services:
  - type: web
    name: crocs-bidder
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.serve:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
